### ISSUE TITLE
感谢开源！

### ISSUE THREAD

**Issue by iHTCboy** [Yueoaix/SymbolicatorX#2]
感谢开源分享！

安装 ipa 和查看路径都是iOS开发的痛点，另外“App 沙盒内文件浏览与导出”，请问可以做一个电脑文档导入到沙盒目录里的功能吗？

另外，想了解一下这些功能的实现，请问有相关的文章吗，thanks~

**Comment by Yueoaix** [comment]
@iHTCboy
目前已添加沙盒文件[上传与删除]的功能,App与手机设备交互功能使用的是 [libimobiledevice](https://github.com/libimobiledevice/libimobiledevice) 库实现的,相关的文章比较少,可以在这里查看该库的 [接口文档 ](https://docs.libimobiledevice.org/libimobiledevice/latest/).

**Comment by iHTCboy** [comment]
@Yueoaix 
好的，非常感谢！

![](https://github.com/Yueoaix/SymbolicatorX/blob/master/SymbolicatorX/SymbolicatorX/Assets.xcassets/AppIcon.appiconset/appiconMacHuge_512pt.png)

**Comment by iHTCboy** [comment]
@Yueoaix 

感谢，我看了一下代码，还在理解中，有空深研一下。另外，我有以下2个需求：

1、实现越狱设备的全目录读取？ 
2、当前链接的设备屏幕进行截图？

不知道大佬有没有想法？我也打算研究一下这些功能，谢谢开源~

**Comment by Yueoaix** [comment]
@iHTCboy 
1.如果设备已越狱,可以通过 "com.apple.afc2" 服务,查看设备文件系统的完整视图.注意只有较旧的越狱软件在设备上安装了AFC2服务.目前我手上没有越狱设备,需要你自己验证一下是否可行.可以参考这个项目 [ifuse](https://github.com/libimobiledevice/ifuse) .
2.已添加 [屏幕截图] 功能

**Comment by iHTCboy** [comment]
@Yueoaix 👍 感谢！这就是开发中经常的痛点，现在 pp 助手都放弃了 Mac 版本，再次感谢大佬开源~
