### ISSUE TITLE
大 ipa 文件安装失败

### ISSUE THREAD

**Issue by iHTCboy** [Yueoaix/SymbolicatorX#3]
1.8G 的ipa 文件安装失败，用了 iMazing 可以安装。

日志就输出：`muxError`

报错的截图：
![Shot_20201106_130059](https://user-images.githubusercontent.com/11418363/98328495-d5a7e000-2030-11eb-8623-52b42eaea1ea.png)

@Yueoaix  大佬有空帮助看看啊

> 一百多 MB 的微信插件包可以安装，之前尝试其它的 ipa 也可以安装，今天就遇到这个问题，不知道是不是文件太大导致？

**Comment by Yueoaix** [comment]
@iHTCboy 
大 iPA 文件上传到手机时间超过10秒,导致 lockdownClient 连接断开, 需要上传完文件后再重新连接一次. Bug 已修复, 可以拉最新代码验证一下.

**Comment by iHTCboy** [comment]
@Yueoaix 可以安装啦，感谢！
