### ISSUE TITLE
The operation couldn’t be completed. (SymbolicatorX.LockdownError error 11.)

### ISSUE THREAD

**Issue by iHTCboy** [Yueoaix/SymbolicatorX#4]
> Error
> The operation couldn’t be completed. (SymbolicatorX.LockdownError error 11.)

选择不同 app 目录时（大概5~6次就出现），提示报错，具体原因我太不清楚，大佬有时间看看啊，感谢！

日志无输出，截图：

![image](https://user-images.githubusercontent.com/11418363/100218401-ac071800-2f4f-11eb-9ce1-6787fcefa969.png)

![image](https://user-images.githubusercontent.com/11418363/100218351-9b56a200-2f4f-11eb-8f5a-74dd052707f1.png)

**Comment by Yueoaix** [comment]
@iHTCboy 
该Bug产生原因是切换 App 时没有释放 house_arrest 服务,目前已修复.
感谢反馈!

**Comment by iHTCboy** [comment]
@Yueoaix 好的，感谢修复~
