### ISSUE TITLE
求助，不支持 Apple Silicon 的 Mac，编译会报错

### ISSUE THREAD

**Issue by iHTCboy** [Yueoaix/SymbolicatorX#5]
Xcode12.2 打包编译错误，因为是这几个库不支持 Arm64 框架，Apple Silicon 设备直接编译也报错啊，大佬有空兼容一下啊

![image](https://user-images.githubusercontent.com/11418363/100320759-a1ef2300-2ffc-11eb-91b6-86448daa43fd.png)

![image](https://user-images.githubusercontent.com/11418363/100320770-a7e50400-2ffc-11eb-9ae9-d6e70190b560.png)

**Comment by Yueoaix** [comment]
@iHTCboy 
已修复

**Comment by iHTCboy** [comment]
@Yueoaix 感谢大佬！
